## Deliverable 3. Create a Travel Itinerary Map.

In [21]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [4]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,1,Geraldton,AU,66.13,overcast clouds,-28.7667,114.6000,Broadwater Mariner Resort
1,3,Georgetown,MY,87.73,few clouds,5.4112,100.3354,Cititel Penang
2,9,Atuona,PF,78.42,few clouds,-9.8000,-139.0333,Villa Enata
3,10,Thompson,CA,60.96,overcast clouds,55.7435,-97.8558,Burntwood Hotel
4,11,Great Yarmouth,GB,63.45,overcast clouds,52.6083,1.7305,Comfort Hotel Great Yarmouth

In [6]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<d1>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp}°F</dd>
</d1>

"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [7]:
# 4a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
vacation_df.set_index("City_ID", inplace=True)
vacation_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
City_ID,,,,,,,
1,Geraldton,AU,66.13,overcast clouds,-28.7667,114.6000,Broadwater Mariner Resort
3,Georgetown,MY,87.73,few clouds,5.4112,100.3354,Cititel Penang
9,Atuona,PF,78.42,few clouds,-9.8000,-139.0333,Villa Enata
10,Thompson,CA,60.96,overcast clouds,55.7435,-97.8558,Burntwood Hotel
11,Great Yarmouth,GB,63.45,overcast clouds,52.6083,1.7305,Comfort Hotel Great Yarmouth
...,...,...,...,...,...,...,...
660,Long Xuyen,VN,78.75,overcast clouds,10.3833,105.4167,Nhà Nghỉ Sài Gòn Ngày Đêm
662,Paso De Los Toros,UY,65.16,overcast clouds,-32.8167,-56.5167,Complejo Isabelino
663,Jardim,BR,69.35,clear sky,-21.4803,-56.1381,Estancia Hotel - Jardim MS
664,Port Augusta,AU,60.94,clear sky,-32.5000,137.7667,Majestic Oasis Apartments
665,Gallup,US,68.76,broken clouds,35.5281,-108.7426,El Capitan Motel

In [26]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df["City"] == "Mount Isa"]
vacation_end = vacation_df.loc[vacation_df["City"] == "Mount Isa"]
vacation_stop1 = vacation_df.loc[vacation_df["City"] == "Caloundra"]
vacation_stop2 = vacation_df.loc[vacation_df["City"] == "Nelson Bay"]
vacation_stop3 = vacation_df.loc[vacation_df["City"] == "Port Augusta"]

In [29]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start["Lat"].to_numpy()[0], vacation_start["Lng"].to_numpy()[0]
end = vacation_start["Lat"].to_numpy()[0], vacation_start["Lng"].to_numpy()[0]
stop1 = vacation_stop1["Lat"].to_numpy()[0], vacation_stop1["Lng"].to_numpy()[0]
stop2 = vacation_stop2["Lat"].to_numpy()[0], vacation_stop2["Lng"].to_numpy()[0]
stop3 = vacation_stop3["Lat"].to_numpy()[0], vacation_stop3["Lng"].to_numpy()[0]

In [33]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
city_itinerary = gmaps.directions_layer(start, end, waypoints =[stop1, stop2, stop3], travel_mode="DRIVING")
fig.add_layer(city_itinerary)
fig

Figure(layout=FigureLayout(height='420px'))

In [35]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Mount Isa,AU,69.57,clear sky,-20.7333,139.5000,ibis Styles Mt Isa Verona
1,Caloundra,AU,72.05,clear sky,-26.8000,153.1333,Watermark Resort Caloundra
2,Nelson Bay,AU,60.01,clear sky,-32.7167,152.1500,Mantra Nelson Bay
3,Port Augusta,AU,60.94,clear sky,-32.5000,137.7667,Majestic Oasis Apartments

In [38]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<d1>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp}°F</dd>
</d1>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [39]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure()
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))